hotreload pgbouncer certs

diff --git a/prototype/package/pgbouncer/pgbouncer-server b/prototype/package/pgbouncer/pgbouncer-server
--- a/prototype/package/pgbouncer/pgbouncer-server
+++ b/prototype/package/pgbouncer/pgbouncer-server
@@ -1,3 +1,25 @@
 #!/bin/sh
 while ! test -f /var/run/postgresql/.migration.done; do sleep 1; done
+
+setup_tls_hot_reload() {
+    if ! grep -q -E "^[[:space:]]*client_tls_sslmode[[:space:]]*=[[:space:]]*require" /vela/config/pgbouncer_pg18.ini; then
+        return 0
+    fi
+
+    echo "TLS explicitly required by configuration. Waiting for certificates..."
+    while ! test -f /vela/certs/tls.key || ! test -f /vela/certs/tls.crt; do sleep 1; done
+    echo "Certificates found. Starting hot-reload watcher in background..."
+
+    (
+      while true; do
+          inotifywait -e modify,create,delete,move /vela/certs > /dev/null 2>&1
+          echo "Certificates modified, reloading PgBouncer..."
+          killall -HUP pgbouncer
+          sleep 2
+      done
+    ) &
+}
+
+setup_tls_hot_reload
+
 /usr/sbin/pgbouncer /vela/config/pgbouncer_pg18.ini 2>&1 | tee /tmp/service-pgbouncer.fifo
